---
master:
  components:
    - apiserver
    - scheduler
    - controllermanager
    - etcd
    - kubernetes
    - kubelet
    - psa

  kubernetes:
    confs:
      - /etc/rancher/rke2/config.yaml
    defaultconf: /etc/rancher/rke2/config.yaml

  apiserver:
    bins:
      - kube-apiserver
    confs:
      - /var/lib/rancher/rke2/agent/pod-manifests/kube-apiserver.yaml
    defaultconf: /var/lib/rancher/rke2/agent/pod-manifests/kube-apiserver.yaml

  psa:
    bins: []
    confs:
      - /etc/rancher/rke2/rke2-pss.yaml
    defaultconf: /etc/rancher/rke2/rke2-pss.yaml

  scheduler:
    bins:
      - kube-scheduler
    confs:
      - /var/lib/rancher/rke2/agent/pod-manifests/kube-scheduler.yaml
    kubeconfig:
      - /var/lib/rancher/rke2/server/cred/scheduler.kubeconfig
    defaultconf: /var/lib/rancher/rke2/agent/pod-manifests/kube-scheduler.yaml
  
  controllermanager:
    bins:
      - kube-controller-manager
    confs:
      - /var/lib/rancher/rke2/agent/pod-manifests/kube-controller-manager.yaml
    kubeconfig:
      - /var/lib/rancher/rke2/server/cred/controller.kubeconfig
    defaultconf: /var/lib/rancher/rke2/agent/pod-manifests/kube-controller-manager.yaml
  
  etcd:
    bins:
      - etcd
    datadirs:
      - /var/lib/rancher/rke2/server/db/etcd
    defaultconf: /var/lib/rancher/rke2/agent/pod-manifests/etcd.yaml

  kubelet:
    bins:
      - "kubelet"
    confs:
      - "/var/lib/rancher/rke2/agent/etc/kubelet.conf.d/00-rke2-defaults.conf"
    defaultconf: "/var/lib/rancher/rke2/agent/etc/kubelet.conf.d/00-rke2-defaults.conf"


node:
  components:
    - kubelet
    - proxy
    # kubernetes is a component to cover the config file /etc/kubernetes/config that is referred to in the benchmark
    - kubernetes

  kubernetes:
    defaultconf: "/etc/kubernetes/config"

  kubelet:
    cafile:
      - "/var/lib/rancher/rke2/agent/server.crt"
      - "/var/lib/rancher/rke2/agent/client-ca.crt"
    bins:
      - "kubelet"
    kubeconfig:
      - "/var/lib/rancher/rke2/agent/kubelet.kubeconfig"
    confs:
      - "/var/lib/rancher/rke2/agent/etc/kubelet.conf.d/00-rke2-defaults.conf"
    defaultconf: "/var/lib/rancher/rke2/agent/etc/kubelet.conf.d/00-rke2-defaults.conf"
    defaultkubeconfig: "/etc/kubernetes/kubelet.conf"
    defaultcafile: "/etc/kubernetes/pki/ca.crt"

  proxy:
    optional: true
    bins:
      - "kube-proxy"
      - "proxy"
      - "containerd"
    confs:
      - /etc/kubernetes/proxy
      - /etc/kubernetes/addons/kube-proxy-daemonset.yaml
      - /var/snap/kube-proxy/current/args
    kubeconfig:
      - /etc/kubernetes/kubelet-kubeconfig
      - /etc/kubernetes/ssl/kubecfg-kube-proxy.yaml
      - /var/lib/rancher/rke2/agent/kubeproxy.kubeconfig
    svc:
      - "/lib/systemd/system/kube-proxy.service"
    defaultconf: /etc/kubernetes/addons/kube-proxy-daemonset.yaml
    defaultkubeconfig: "/etc/kubernetes/proxy.conf"

etcd:
  components:
    - etcd

  etcd:
    bins:
      - "etcd"
      - "containerd"
    confs:
      - /var/lib/rancher/rke2/agent/pod-manifests/etcd.yaml
    defaultconf: /etc/kubernetes/manifests/etcd.yaml

version_mapping:
  "v1.31.0+rke2r1": "rke2-stig-1.31"

target_mapping:
  "rke2-stig-1.31":
    - "node"
    - "etcd"
    - "master"
